Extend ptp4l template
LMAX-Exchange/puppet-linuxptp pull request #1
Opened 2017-11-02 14:24 UTC by gerhard-tinned

Extended the template for ptp4l with the following variables:

* delay_mechanism
* time_stamping

2017-11-02 19:06 UTC, lukebigum requested changes
The validate_re error message here still says "delay_mechanism" instead of "time_stamping".

2017-11-02 19:06 UTC, lukebigum commented on manifests/ptp4l.pp
> +  validate_re($time_stamping, ['hardware', 'software'], "Parameter 'delay_mechanism' must be one of 'hardware' or 'software'")
The validate_re error message here still says "delay_mechanism" instead of "time_stamping".

2017-11-02 19:09 UTC, lukebigum commented
Other than the error message, it looks fine. I'll spend a bit of time getting the actual tests to pass in Travis tomorrow.

2017-11-03 10:33 UTC, merged

2017-11-08 15:08 UTC, gerhard-tinned commented
Thanks for fixing the mistake in the error message.